### ISSUE TITLE
JLCPCB Library?

### ISSUE THREAD

**Issue by rljacobson** [NiklasFauth/jlcsmt-kicad-converter#2]
Hi, Niklas. I found you via Google, which picked up your Twitter.

I literally just committed [this scraped list of "Basic Library" parts](https://github.com/rljacobson/JLCPCBBasicLibrary) right before I found your repo. Unfortunately, to filter by "library type" I had to use the Chinese language website, which is more feature full than the English language site. I'm curious where you got the CSV data. Did you scrape the English langauge website? In retrospect, that would have been easier for me as well, but I was fixated on only getting the "Basic Library" components and missed the obvious! On the other hand, maybe there's already a CSV source? Hence my question.

Thanks!

**Comment by lucysrausch** [comment]
Hey!

I got the data from this link I found somewhere on the JLCSMT website.
https://jlcpcb.com/video/jlcsmt_parts_library.xls

I don't know if it's up to date, but the content changes from time to time.
